### ISSUE TITLE
Ajuda com os Resolvers

### ISSUE THREAD

**Issue by ghost** [Flutterando/dson_adapter#12]
Olá, estou com uma duvida sobre os Resolvers de um DSON.fromJson().

Eu tenho um DateTime nullable (DateTime?) e preciso de um resolver pra ele por causa do DateTime.parse.

Segue o print:

![fromJson Dson](https://github.com/Flutterando/dson_adapter/assets/50329928/b63fe446-7759-4c6d-bdaf-ad1f854d3f56)

Porém o resolver não permite voltar "null" no return do value dele:

![print erro](https://github.com/Flutterando/dson_adapter/assets/50329928/290a8398-231b-4bef-89d1-76d80000ee65)

Preciso que fique algo parecido com uma validação que permita o objeto nullable ser nulo conforme na imagem abaixo:

![fromJson padrao](https://github.com/Flutterando/dson_adapter/assets/50329928/02089fdb-6159-46ef-8629-052e016b07a4)

Como que posso resolver esse problema?

**Comment by noemyroberta** [comment]
Olá,
uma sugestão é criar um valor `default` para DateTime, no mesmo formato que você gostaria de receber caso `value != null`.
```dart
void main() {
  print('Return a datetime default when value is empty');
  final json = {"dataCadastro": null};

  FormularioModel model = FormularioEntity.fromJson(json);
  print(model); // dataCadastro: -0001-11-30 00:00:00.000
}

class FormularioModel {
  DateTime? dataCadastro;

  FormularioModel({this.dataCadastro});

  @override
  String toString() {
    return "dataCadastro: $dataCadastro";
  }
}

class FormularioEntity {
  FormularioEntity._();

  static FormularioModel fromJson(Map<String, dynamic> json) {
    return const DSON().fromJson(json, FormularioModel.new, resolvers: [
      (key, value) {
        if (key == 'dataCadastro' && value != null) {
          return DateTime.parse(value);
        } else {
          return DateTime(0, 0, 0);
        }
      }
    ]);
  }
}```
