### ISSUE TITLE
Problema com List<int>

### ISSUE THREAD

**Issue by victor-castro** [Flutterando/dson_adapter#13]
Olá,
Hoje me deparei com o seguinte erro: 
`Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'List<num>?' of 'durations'`

Consigo representar List<int> de alguma forma ou seria um bug mesmo?

**Comment by Zeca-dev** [comment]
Tem que usar List<Param> nesse caso, como objeto inner.
