### ISSUE TITLE
Lista de Strings

### ISSUE THREAD

**Issue by munhozfontana** [Flutterando/dson_adapter#4]
Tem possibilidade de fazer um exemplo utilizando uma lista de strings?

exemplo de json:
`{
      'destination_addresses': ['Philadelphia, PA, USA'],
      'origin_addresses': ['New York, NY, USA'],
      'rows': [
        {
          'elements': [
            {
              'distance': {'text': '94.6 mi', 'value': 152193},
              'duration': {'text': '1 hour 44 mins', 'value': 6227},
              'status': 'OK'
            }
          ]
        }
      ],
      'status': 'OK'
    };`

Valeu

**Comment by jacobaraujo7** [comment]
Feito! 
v1.2.0
