### ISSUE TITLE
Mensagens de erro personalizadas

### ISSUE THREAD

**Issue by andre-djsystem** [Flutterando/dson_adapter#7]
Estou iniciando em flutter e tentei implementar a possibilidade de customizar as mensagens de erro, iniciei a implementação neste repositório - https://github.com/andre-djsystem/dson_adapter

Não estou conseguindo realizar a interpolação das variáveis passadas dentro de uma string, é possivel?

![image](https://user-images.githubusercontent.com/49646398/231796739-906609c6-e587-4c3d-825c-d0d8f46e9856.png)

**Comment by jacobaraujo7** [comment]
Olá, 
Eu realmente nao compreendi pq isso não pode ser feito.
Houve alguma mudança no seu fork?

**Comment by emanuel-braz** [comment]
@andre-djsystem  O Dart permite fazer interpolação com variáveis, o problema pelo que eu percebi é que você não tem uma referência para a variável que você quer usar, por isso não tem como interpolar a "variável que não existe". 

O `\` antes de um character serve para fazer escape desse character(pode gerar resultados diferentes dependendo do character), no seu caso está tornando tudo em uma string literal(raw), que não é o que você precisa. 

ex: 
```dart
final variavelExiste = 'Person';
// final variavelNaoExiste = 'Person';

print('O nome da classe é $variavelExiste'); // imprime "O nome da classe é Person"
print('O nome da classe é $variavelNaoExiste'); // Não compila o código, pois não há referência para uma variável dentro do escopo
print('O nome da classe é \$variavelNaoExiste'); // imprime "O nome da classe é $variavelNaoExiste"
print(r'O nome da classe é $variavelNaoExiste'); // imprime "O nome da classe é $variavelNaoExiste"
```

Uma dica, pense na possibilidade de utilizar callbacks que exponham as variáveis que vc quer usar, dai vc poderá interpolar a vontade.

**Comment by andre-djsystem** [comment]
Se puder verificar a implementação https://github.com/andre-djsystem/dson_adapter/commit/5700543f3451148e7d00c1a7fd2c5f9df2e920f1 verá que os nomes de variáveis passadas como parâmetro não são interpoladas.

![image](https://user-images.githubusercontent.com/49646398/232455536-cef42c15-6991-439b-879c-a5bba2c2ad88.png)

No teste acima, ao invés de retornar "The parameter Person.id was not informed" é retornado "The parameter $className.${param.name} was not informed"

**Comment by jacobaraujo7** [comment]
Vou fechar essa issue, pois não parece um problema do package em si.
